### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by lazovicff**

### CODE REVIEW

**Review by 4rmanc — DISMISSED** [review]

**Review by duguorong009 — DISMISSED** [review]
Thanks!  :rocket:

**Review by duguorong009 — APPROVED** [review]

**Comment by lazovicff** [comment]
@duguorong009 Can you re-review this? I think its ready now

**Review by duguorong009 — COMMENTED** [review]
First of all, thanks for fixes! :+1: 
I checked the branch in my local machine & it works! :raised_hands: 

One question from curiosity.
You moved the `foundry(anvil)` install script from local to github CI.
Do you want the tests(related to `anvil`) to run in only CI, not local machines?

If so, what should I do for running those tests on local machine? just install `anvil`?

**Review by duguorong009 — APPROVED** [review]

**Comment by lazovicff** [comment]
The tests are meant to run both locally and on CI.
The scripts inside ./scripts folder are only meant for Ubuntu linux which is used inside CI.
Locally, we should manually install all dependencies.
Here are the instructions for foundry:
https://github.com/foundry-rs/foundry#installation

**Comment by duguorong009** [comment]
> The tests are meant to run both locally and on CI. The scripts inside ./scripts folder are only meant for Ubuntu linux which is used inside CI. Locally, we should manually install all dependencies. Here are the instructions for foundry: https://github.com/foundry-rs/foundry#installation

okay, thanks for the info! :+1:

**Pull request merged**
