### PR TITLE
feat(circuit): refactor the halo2 circuit columns

### LINKED ISSUE #173: CommonConfig - number of columns
Think about how many columns we need to meet the scalability requirements.
Think about if we want to optimise it for smart contract verifiers

### PR DESCRIPTION
**Pull request by duguorong009**
## Description
- Increase the circuit columns - 20 advice, 10 fixed 
- Refactor the configuration of some chips used in Halo2 circuit

## Related issues
Closes #173 

## Changes
- Update the `circuit/lib.rs` - `CommonConfig` constants
- Update the `circuit/gadgets/main.rs` - `MainChip` and related chipsets
- Update the `circuit/integer/*` - `Integer`-related chips

### CODE REVIEW

**Comment by lazovicff** [comment]
We should add 1 TableColumn inside CommonConfig as well

**Comment by lazovicff** [comment]
Now that we have this setup, can you lower the k parameter in cases where MainGate and Integers/Ecc are used?

**Comment by duguorong009** [comment]
> We should add 1 TableColumn inside CommonConfig as well

Added `TableColumn` in [here](https://github.com/eigen-trust/protocol/pull/286/commits/1b1c751219fd76196b6f6d581dd3704321295d35)

**Comment by duguorong009** [comment]
> Now that we have this setup, can you lower the k parameter in cases where MainGate and Integers/Ecc are used?

Yes. In fact, I tried to lower the k parameter in any possible cases.([here](https://github.com/eigen-trust/protocol/pull/286/commits/d0ae3e76c85ebc1ce6967a8171a341c9d1998000) and [here](https://github.com/eigen-trust/protocol/pull/286/commits/f812e8bc5b89396047587c64fa578f27e462bcf0))

**Review by lazovicff — APPROVED** [review]

**Pull request merged**
