### PR TITLE
Create `threshold` module

### LINKED ISSUE #231: Move `check_threshold` to a separate module
Move the functionality for checking the score threshold to a separate module, inside the `native.rs` file.

The file structure:
- `threshold`
  - `mod.rs` - Empty file that imports the native version;
  - `native.rs` - Native version of the circuit

The struct:
```rust
struct Threshold<F: FieldExt, const NUM_LIMBS: usize, const POWER_OF_TEN: usize> {
  score: F,
  ratio: BigRational,
  threshold: F,
}
```

### PR DESCRIPTION
**Pull request by duguorong009**
## Description
- Create separate module for logic of checking threshold of scores

Closes #231 

## Changes
- Create files for native and halo2 version of `threshold` module
- Implement the native version

### CODE REVIEW

**Comment by lazovicff** [comment]
Can we add 1 or two tests?

**Comment by lazovicff** [comment]
I think `converge` and `converge_rational` are redundant. We just need to test the Threshold in isolation

**Comment by lazovicff** [comment]
@duguorong009 I added new test cases to help you understand how threshold checks work.

**Review by lazovicff — DISMISSED** [review]

**Comment by lazovicff** [comment]
@duguorong009 I will merge once the print statements are removed

**Comment by duguorong009** [comment]
> @duguorong009 I will merge once the print statements are removed

Ouch. 
Yes, I will remove the print statements.

**Review by lazovicff — APPROVED** [review]

**Pull request merged**
